# 基本配置
title: Light time/轻时光
description: Light time/轻时光,周丹的个人博客,blog,jekyll,github
baseurl: ""
url: "http://zdan.me"
author: zdan

# 联系方式
email: iou012345@163.com
twitter_username:
github_username: zdan

# 分页设置
paginate: 5
paginate_path: /page/:num

# Markdown配置
markdown: kramdown

# 版权
copyright: © zdan.me 2015

# 侧边栏
sidebar:
  job: Node.js、Web前端
  say: “未来总是充满冒险的味道”
  img: /assets/images/bg11.jpeg
