# 基本配置
title: 离子
description: 离子的技术博客，平时会分享和记录一些自己感兴趣的技术，如：node.js开发等。
keywords: zdan.me,博客
baseurl: ""
url: "http://zdan.me"
author: zdan

# post路由
permalink: /:categories/:year/:month/:day/:title.html

# 联系方式
email: aW91MDEyMzQ1QDE2My5jb20=
github_username: zdan

# 分页设置
paginate: 5
paginate_path: /page/:num

# Markdown配置
# markdown: kramdown

highlighter: pygments
markdown: redcarpet
extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

# 版权
copyright: © zdan.me 2015

# 侧边栏
sidebar:
  job: Node.js
  say: 心之所向
  bg: http://7xi82w.com1.z0.glb.clouddn.com/imgbg11.jpeg
  author_img: http://7xi82w.com1.z0.glb.clouddn.com/me.jpeg
